services:
  plone:
    build:
      context: ./plone
    image: 4teamwork/plone:4.3.20
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"

  zeoserver:
    build:
      context: ./zeoserver
    image: 4teamwork/zeoserver:4.3.20
    volumes:
      - ./data:/data
