version: '3'

services:
  plone:
    build:
      context: ./plone
    image: 4teamwork/plone:latest
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    environment:
      - STORAGE=zeoclient
  zeoserver:
    build:
      context: ./zeoserver
    image: 4teamwork/zeoserver:latest
    volumes:
      - ./data:/data
